Repository 3scale-sre/test-infra, pull requests merged in 2021-04, with the labels that each got.

#7 feat: Add GH team export helper
  hack/export-gh-org-members/.gitignore
  hack/export-gh-org-members/Dockerfile
  hack/export-gh-org-members/Gemfile
  hack/export-gh-org-members/Gemfile.lock
  hack/export-gh-org-members/Makefile
  hack/export-gh-org-members/README.md
  hack/export-gh-org-members/export-org-teams.rb
Labels: approved, kind/feature, lgtm, priority/important-longterm, size/S

#8 Feat/add label management
  .github/workflows/label-sync.yaml
  hack/label_sync/.gitignore
  hack/label_sync/Makefile
  hack/label_sync/README.md
  hack/label_sync/labels.yaml
  manifests/prow/configmaps/plugins.yaml
Labels: approved, kind/feature, lgtm, priority/important-soon, size/S

#10 Config: Setup prow plugins
  hack/label_sync/labels.yaml
  manifests/prow/configmaps/config.yaml
  manifests/prow/configmaps/plugins.yaml
  manifests/prow/deployments/hook.yaml
Labels: approved, kind/feature, lgtm, priority/important-soon, size/L

#11 docs: add label documentation
  hack/label_sync/Makefile
  hack/label_sync/README.md
  hack/label_sync/README.md.tpl
  hack/label_sync/labels.yaml
Labels: approved, kind/documentation, lgtm, priority/important-longterm, size/S

#14 Cleanup: Remove layer labels
  hack/label_sync/README.md
  hack/label_sync/labels.yaml
  manifests/prow/configmaps/plugins.yaml
Labels: approved, kind/documentation, lgtm, priority/important-longterm, size/S

#13 Config: Enable owners labels
  OWNERS
  OWNERS_ALIASES
  manifests/prow/configmaps/plugins.yaml
Labels: approved, kind/feature, lgtm, priority/important-soon, size/S

#15 Docs: Add GitHub templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/automation, kind/documentation, lgtm, priority/important-longterm, size/S

#16 feat: enable size pluging for PRs
  manifests/prow/configmaps/plugins.yaml
Labels: approved, kind/automation, kind/feature, lgtm, priority/important-longterm, size/XS

#17 config: update size plugin threshold
  manifests/prow/configmaps/plugins.yaml
Labels: approved, kind/feature, lgtm, priority/important-longterm, size/S

#18 Feat/add pro saas label
  README.md
  hack/label_sync/Makefile
  hack/label_sync/README.md
  hack/label_sync/labels.yaml
Labels: approved, kind/documentation, lgtm, priority/important-soon, size/S
