Repository 3scale-sre/test-infra, pull requests merged in 2025-05, with the labels that each got.

#56 feat: enable manual execuiton of gh actions
  .github/workflows/label-sync.yaml
Labels: approved, lgtm, priority/important-soon, size/XS, kind/feature, wg/sre

#57 Revert "feat: enable manual execuiton of gh actions"
  .github/workflows/label-sync.yaml
Labels: approved, lgtm, priority/important-soon, size/XS, kind/cleanup, wg/sre

#59 Feat/Add deploy and dev-eng labels to 3scale-saas-dev
  hack/label_sync/README.md
  hack/label_sync/labels.yaml
Labels: approved, lgtm, needs-priority, size/M, kind/documentation, wg/sre
